export const PHONE_CODES = [
  { code: '+57', flag: '🇨🇴', label: 'Colombia' },
  { code: '+58', flag: '🇻🇪', label: 'Venezuela' },
  { code: '+593', flag: '🇪🇨', label: 'Ecuador' },
  { code: '+51', flag: '🇵🇪', label: 'Perú' },
  { code: '+52', flag: '🇲🇽', label: 'México' },
  { code: '+1',  flag: '🇺🇸', label: 'USA' },
  { code: '+34', flag: '🇪🇸', label: 'España' },
];

export const CITIES_BY_DEPARTMENT: Record<string, string[]> = {
  'Amazonas':                   ['Leticia', 'Puerto Nariño'],
  'Antioquia':                  ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Apartadó', 'Turbo', 'Rionegro', 'Caucasia', 'Sabaneta', 'Copacabana', 'La Estrella'],
  'Arauca':                     ['Arauca', 'Saravena', 'Tame', 'Fortul', 'Arauquita'],
  'Atlántico':                  ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Baranoa', 'Puerto Colombia', 'Galapa', 'Palmar de Varela'],
  'Bogotá D.C.':                ['Bogotá'],
  'Bolívar':                    ['Cartagena', 'Magangué', 'Turbaco', 'Arjona', 'El Carmen de Bolívar', 'Mompox', 'San Juan Nepomuceno'],
  'Boyacá':                     ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa', 'Monguí', 'Villa de Leyva', 'Puerto Boyacá'],
  'Caldas':                     ['Manizales', 'Villamaría', 'La Dorada', 'Riosucio', 'Chinchiná', 'Anserma', 'Supía'],
  'Caquetá':                    ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'El Doncello', 'La Montañita'],
  'Casanare':                   ['Yopal', 'Aguazul', 'Villanueva', 'Paz de Ariporo', 'Tauramena', 'Monterrey'],
  'Cauca':                      ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Guapi', 'Piendamó', 'El Tambo'],
  'Cesar':                      ['Valledupar', 'Aguachica', 'Codazzi', 'La Jagua de Ibirico', 'Bosconia', 'Chimichagua'],
  'Chocó':                      ['Quibdó', 'Istmina', 'Riosucio', 'Tadó', 'Condoto', 'Bahía Solano', 'Nuquí'],
  'Córdoba':                    ['Montería', 'Lorica', 'Cereté', 'Sahagún', 'Planeta Rica', 'Montelíbano', 'San Pelayo'],
  'Cundinamarca':               ['Soacha', 'Fusagasugá', 'Chía', 'Zipaquirá', 'Facatativá', 'Mosquera', 'Madrid', 'Funza', 'Girardot', 'Cajicá', 'Tocancipá', 'La Calera'],
  'Guainía':                    ['Inírida'],
  'Guaviare':                   ['San José del Guaviare', 'Calamar', 'El Retorno', 'Miraflores'],
  'Huila':                      ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre', 'Rivera'],
  'La Guajira':                 ['Riohacha', 'Maicao', 'Uribia', 'Manaure', 'Albania', 'Dibulla'],
  'Magdalena':                  ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato', 'Aracataca'],
  'Meta':                       ['Villavicencio', 'Acacías', 'Granada', 'Cumaral', 'Puerto López', 'Puerto Gaitán', 'Restrepo'],
  'Nariño':                     ['Pasto', 'Tumaco', 'Ipiales', 'Túquerres', 'La Unión', 'Samaniego', 'Barbacoas'],
  'Norte de Santander':         ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios', 'El Zulia', 'Tibú'],
  'Putumayo':                   ['Mocoa', 'Puerto Asís', 'Valle del Guamuez', 'Sibundoy', 'Orito', 'San Miguel'],
  'Quindío':                    ['Armenia', 'Calarcá', 'Quimbaya', 'Montenegro', 'La Tebaida', 'Circasia', 'Filandia'],
  'Risaralda':                  ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Belén de Umbría', 'Quinchía'],
  'San Andrés y Providencia':   ['San Andrés', 'Providencia'],
  'Santander':                  ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta', 'Barrancabermeja', 'Socorro', 'San Gil', 'Málaga'],
  'Sucre':                      ['Sincelejo', 'Corozal', 'Sampués', 'Tolú', 'San Marcos', 'Morroa', 'Ovejas'],
  'Tolima':                     ['Ibagué', 'Espinal', 'Melgar', 'Líbano', 'Chaparral', 'Honda', 'Mariquita', 'Flandes'],
  'Valle del Cauca':            ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Buga', 'Cartago', 'Jamundí', 'Yumbo', 'Candelaria', 'Florida'],
  'Vaupés':                     ['Mitú'],
  'Vichada':                    ['Puerto Carreño', 'La Primavera', 'Santa Rosalía'],
};

export const DEPARTMENTS = Object.keys(CITIES_BY_DEPARTMENT).sort();
